version: '3.8'

services:
  onco-emr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onco-emr-app
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
